-- AlterTable
ALTER TABLE "RestaurantTable" ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "posX" INTEGER,
ADD COLUMN     "posY" INTEGER,
ADD COLUMN     "rotation" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "shape" TEXT NOT NULL DEFAULT 'square',
ADD COLUMN     "width" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "Zone" ADD COLUMN     "gridCols" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "gridRows" INTEGER NOT NULL DEFAULT 10;
